# Generated by Django 5.0.6 on 2025-05-25 18:41

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Enter Category')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='blog_images', verbose_name='Image')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Put a Title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=100, verbose_name='Enter Author Name')),
                ('description', ckeditor.fields.RichTextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blogs.category', verbose_name='Select Category')),
            ],
        ),
    ]
