# Generated by Django 5.0.6 on 2025-05-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('files', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_section', models.CharField(choices=[('hero', 'Hero'), ('middle', 'moddle'), ('card', 'card'), ('intro', 'Introduction')], max_length=50)),
                ('page_name', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('survey', 'Survey')], max_length=50)),
            ],
        ),
    ]
