# Generated by Django 5.0.6 on 2025-05-26 21:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0002_mainmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('survey', 'Survey'), ('train&FAQ', 'Train&FAQ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mainmodel',
            name='page_section',
            field=models.CharField(choices=[('hero', 'Hero'), ('middle', 'moddle'), ('card', 'card'), ('intro', 'Introduction'), ('down', 'Down')], max_length=50),
        ),
    ]
