# Generated by Django 5.0.6 on 2025-05-26 22:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0003_alter_mainmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
