# Generated by Django 5.0.6 on 2025-05-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_design', '0004_alter_surveyquestion_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
